### PR TITLE
Feature1

### PR DESCRIPTION
**Pull request by aristides1000**
## What this PR does
This PR adds the greyscale heat map of the main page

## Screenshot
image

### CODE REVIEW

**Comment by aristides1000** [comment]
I don't know why, I get that rare error when I run webhint, could you help me understand what is happening?

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @aristides1000 and @danielufeli :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this project can be approved.

## REQUIRED

* [x] Your Pull Request message should be descriptive. It should contain a short message about what you accomplished in the project
* [x] The whole page is overflowing which is why there's a scroll bar at the bottom of the page. You should fix that
* [x] Do away with unnecessary whitespace
* [x] `MORE LINKS ON TWITTER`, `SEE ALL GUIDES` and `SEE ALL LATEST ARTICLES` should be centred.
* [x] Your page is expected to model the same structure of the original page. You can refer to the following for inspiration:
  * [x] https://eananti.github.io/Smashing-Magazine-Heatmap/
  * [x] https://raw.githack.com/fc-anjos/design-teardown/heatmap/index.html
  * [x] https://raw.githack.com/Bismarck-GM/microverse-design-teardown/development/index.html
  * [x] https://raw.githack.com/anewman15/smashing-magazine-heatmap/master/index.html


### Please, make the requested changes and submit for another review
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by aristides1000** [comment]
En esta ocasión, mi socio de codificación y yo entendimos y aplicamos la importancia de importar fuentes gratuitas desde el portal de Google Fonts, además de eso, aprendimos la importancia y aplicamos el peso visual de los elementos a nuestro portal con el fin de captar la atención de nuestros usuarios, así como la importancia y las diferencias entre UI y UX

**Review by descholar-ceo — APPROVED** [review]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
## :clap: :clap: :clap: Congratulations @aristides1000 and @danielufeli  , your project is approved :tada: :tada: :tada: 
You have implemented all minimum requirements for this project to mark it as complete, it doesn't need more changes, you can go ahead and merge all of the changes on base branch,

Don't forget to fill the mandatory project completion form, and see you to next project,

Happy coding :computer: :computer: :computer: 

Re-reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

**Pull request merged**
